services:
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: manhaw-android
    privileged: true
    devices:
      - /dev/kvm
    ports:
      - "6080:6080"   # noVNC (navigateur)
      - "5555:5555"   # ADB
      - "8080:8080"   # mitmproxy (partagé via network_mode sur mitmproxy)
    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"
    restart: unless-stopped

  mitmproxy:
    image: mitmproxy/mitmproxy:10.4.1
    container_name: manhaw-mitmproxy
    depends_on:
      - android-emulator
    network_mode: "service:android-emulator"
    volumes:
      - ./mitmproxy/addons:/addons:ro
      - ./captures:/captures
      - mitmproxy-home:/home/mitmproxy/.mitmproxy
    command: >
      mitmdump
      --listen-host 0.0.0.0
      --listen-port 8080
      -s /addons/addon_log_api.py
      --set flow_detail=1
    restart: unless-stopped

volumes:
  mitmproxy-home:
